[platformio]
default_envs = m5stack_dial_demo

[env]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
extra_scripts = pre:tools/git_sha.py
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CORE_DEBUG_LEVEL=3
lib_deps =
  m5stack/M5Dial
  m5stack/M5Unified
  m5stack/M5GFX
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  knolleary/PubSubClient@^2.8
  h2zero/NimBLE-Arduino

[env:m5stack_dial]
build_flags =
  ${env.build_flags}
  -D FERM_ENABLE_NETWORK=0
  -D FERM_ENABLE_OTA=0
  -D FERM_DEMO_SENSOR=0

[env:m5stack_dial_demo]
build_flags =
  ${env.build_flags}
  -D FERM_ENABLE_NETWORK=1
  -D FERM_ENABLE_OTA=1
  -D FERM_DEMO_SENSOR=1
  -D FERM_ENABLE_HYDROMETER_BLE=1

[env:m5stack_dial_wifi]
build_flags =
  ${env.build_flags}
  -D FERM_ENABLE_NETWORK=1
  -D FERM_ENABLE_OTA=1
  -D FERM_DEMO_SENSOR=0
  -D FERM_ENABLE_HYDROMETER_BLE=1
